export const ActionTypes={
    SET_USERS:"SET_USERS",
    DELETE_USER:"DELETE_USER",
    SELECTED_USER:"SELECTED_USER",
    REMOVE_SELECTED_USER:"REMOVE_SELECTED_USER",
    SET_SEARCH_BOX:"SET_SEARCH_BOX",
    CREATE_USER:"CREATE_USER",
    UPDATE_USER:"UPDATE_USER"
}